"""Compatibility helpers for staged Red Night package separation."""

from __future__ import annotations

from importlib import import_module
from types import ModuleType

NAMESPACE = "nightrecon_red_engine"
LEGACY_NAMESPACE = "nightrecon"

MIGRATED_MODULES = frozenset({
    "api_execution",
    "api_graphql",
    "api_models",
    "api_openapi",
    "api_planner",
    "api_policy",
    "api_report",
    "api_validation_report",
    "assessment_engine",
    "asset_inventory",
    "asset_inventory_store",
    "browser_playwright",
    "browser_policy",
    "browser_report",
    "browser_worker",
    "builtin_checks",
    "check_catalog",
    "check_feed",
    "check_feed_state",
    "check_pack_manager",
    "check_pack_signing",
    "check_pack_store",
    "check_packs",
    "check_plugins",
    "cisa_kev_provider",
    "config",
    "cpe_identity",
    "credential_providers",
    "credential_resolution",
    "dast_cors",
    "dast_evidence",
    "dast_findings",
    "dast_http",
    "dast_policy",
    "dast_report",
    "discovery_report",
    "epss_provider",
    "graph_assessment",
    "graph_builder",
    "graph_correlation",
    "graph_critical_asset",
    "graph_identity_evidence",
    "graph_identity_projection",
    "graph_index",
    "graph_models",
    "graph_path",
    "graph_path_review",
    "graph_pipeline",
    "graph_projection",
    "graph_query",
    "graph_report",
    "graph_snapshot",
    "graph_summary",
    "graph_threat_context",
    "graph_traversal",
    "graph_validation",
    "graph_web_surface",
    "graphql_report",
    "active_directory_provider",
    "attack_path_atlas",
    "entra_provider",
    "identity_benchmark",
    "identity_collection",
    "identity_engagement_evidence",
    "identity_coverage_review",
    "identity_benchmark_acceptance",
    "identity_operator_summary",
    "host_discovery",
    "infrastructure_database",
    "infrastructure_database_adapter",
    "infrastructure_database_mysql",
    "infrastructure_database_psycopg",
    "infrastructure_execution",
    "infrastructure_models",
    "infrastructure_network_device",
    "infrastructure_policy",
    "infrastructure_registry",
    "infrastructure_report",
    "infrastructure_smb",
    "infrastructure_smb_adapter",
    "infrastructure_smb_impacket",
    "infrastructure_ssh",
    "infrastructure_winrm",
    "infrastructure_winrm_adapter",
    "infrastructure_winrm_pywinrm",
    "logging",
    "nvd_provider",
    "os_fingerprint",
    "ports",
    "red_cli",
    "red_directory_cli",
    "red_directory_import",
    "red_identity_live_cli",
    "red_workspace_cli",
    "report",
    "resolver",
    "security_headers",
    "service_detection",
    "service_fingerprint",
    "service_probe",
    "session",
    "software_identity",
    "storage",
    "tcp_scanner",
    "threat_context",
    "tls_detection",
    "udp_scanner",
    "network_assessment_intelligence",
    "environment_network_intelligence",
    "network_operator_brief",
    "network_context_intelligence",
    "network_change_intelligence",
    "network_evidence_completeness",
    "network_executive_assessment",
    "network_assessment_bundle",
    "network_engagement_executive",
    "network_engagement_change",
    "network_review_readiness",
    "network_follow_up_plan",
    "network_engagement_brief",
    "network_evidence_concentration",
    "network_change_executive",
    "network_engagement_export",
    "remediation_retest",
    "controlled_validation",
    "validation_adapter_contracts",
    "validation_attack_review",
    "validation_candidates",
    "validation_eligibility",
    "validation_techniques",
    "validation_worker",
    "validation_operation_plan",
    "validation_operation_state",
    "validation_operation_handoff",
    "network_benchmark",
    "network_benchmark_report",
    "engagement_review",
    "engagement_report",
    "engagement_export",
    "engagement_collaboration",
    "vulnerability_intelligence",
    "web_active_assessment",
    "web_assessment",
    "web_crawl",
    "web_form_execution",
    "web_form_intent",
    "web_form_submission",
    "web_report",
    "web_workflow",
    "web_workflow_execution",
    "web_workflow_report",
    "web_api_safety_corpus",
})


def is_migrated_module(module_name: str) -> bool:
    return isinstance(module_name, str) and module_name.strip() in MIGRATED_MODULES


def is_red_owned_module(module_name: str) -> bool:
    """Compatibility alias for the Batch A namespace API."""

    return is_migrated_module(module_name)


def existing_module(module_name: str) -> ModuleType:
    """Return a migrated Red module from its canonical Red engine namespace."""

    if not isinstance(module_name, str) or not module_name.strip():
        raise ValueError("module_name must be a nonblank string")
    normalized = module_name.strip()
    if normalized not in MIGRATED_MODULES:
        raise ValueError(f"module is not migrated to Red engine: {normalized}")
    return import_module(f"{NAMESPACE}.{normalized}")
